version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - restore_cache:
          name: restore git cache
          keys:
            - repo-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - repo-v1-{{ arch }}-{{ .Branch }}
            - repo-v1-{{ arch }}
      - checkout
      - save_cache:
          name: save git cache
          key: repo-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: git remote
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
