version: 2.1

jobs:
  build:
    machine: true
    #docker:
    #  - image: cimg/base:stable
    #parallelism: 2
    steps:
      - restore_cache:
          name: restore git cache
          keys:
            #- repo-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - repo-v1-{{ arch }}-{{ .Branch }}
            - repo-v1-{{ arch }}
      - checkout
      - save_cache:
          name: save git cache
          #key: repo-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          key: repo-v1-{{ arch }}-{{ .Branch }}
          paths:
            - ".git"
      - run: git remote
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
